package com.allinfinance.dao.common;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 */
public interface IProcessObj {

    /**
     * Flush.
     */
	public abstract void flush();
}
