package com.allinfinance.po.daytrade;

import java.math.BigDecimal;

// Generated 2015-6-19 10:52:53 by Hibernate Tools 3.4.0.CR1

/**
 * TblWithdrawInf generated by hbm2java
 */

public class TblWithdrawInf implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String batchNo;
	private String wdTime;
	private String wdSeqNum;
	private String mchtNo;
	private String wdNum;
	private BigDecimal sumAmtTrans;
	private BigDecimal wdAmtFee;
	private BigDecimal amtSettlmt;
	private Character wdStatus;
	private String applyOpr;
	private String applyTime;
	private String checkOpr;
	private String checkTime;
	private String refuseReason;
	private String limitAmt;

	public String getBatchNo() {
		return batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	public String getWdTime() {
		return wdTime;
	}

	public void setWdTime(String wdTime) {
		this.wdTime = wdTime;
	}

	public String getWdSeqNum() {
		return wdSeqNum;
	}

	public void setWdSeqNum(String wdSeqNum) {
		this.wdSeqNum = wdSeqNum;
	}

	public String getMchtNo() {
		return mchtNo;
	}

	public void setMchtNo(String mchtNo) {
		this.mchtNo = mchtNo;
	}

	public String getWdNum() {
		return wdNum;
	}

	public void setWdNum(String wdNum) {
		this.wdNum = wdNum;
	}



	public BigDecimal getSumAmtTrans() {
		return sumAmtTrans;
	}

	public void setSumAmtTrans(BigDecimal sumAmtTrans) {
		this.sumAmtTrans = sumAmtTrans;
	}

	public BigDecimal getWdAmtFee() {
		return wdAmtFee;
	}

	public void setWdAmtFee(BigDecimal wdAmtFee) {
		this.wdAmtFee = wdAmtFee;
	}

	public BigDecimal getAmtSettlmt() {
		return amtSettlmt;
	}

	public void setAmtSettlmt(BigDecimal amtSettlmt) {
		this.amtSettlmt = amtSettlmt;
	}

	public Character getWdStatus() {
		return wdStatus;
	}

	public void setWdStatus(Character wdStatus) {
		this.wdStatus = wdStatus;
	}

	public String getApplyOpr() {
		return applyOpr;
	}

	public void setApplyOpr(String applyOpr) {
		this.applyOpr = applyOpr;
	}

	public String getApplyTime() {
		return applyTime;
	}

	public void setApplyTime(String applyTime) {
		this.applyTime = applyTime;
	}

	public String getCheckOpr() {
		return checkOpr;
	}

	public void setCheckOpr(String checkOpr) {
		this.checkOpr = checkOpr;
	}

	public String getCheckTime() {
		return checkTime;
	}

	public void setCheckTime(String checkTime) {
		this.checkTime = checkTime;
	}

	public String getRefuseReason() {
		return refuseReason;
	}

	public void setRefuseReason(String refuseReason) {
		this.refuseReason = refuseReason;
	}

	public String getLimitAmt() {
		return limitAmt;
	}

	public void setLimitAmt(String limitAmt) {
		this.limitAmt = limitAmt;
	}

	
}
