package com.allinfinance.po.base;

// Generated 2016-4-19 15:41:48 by Hibernate Tools 3.4.0.CR1

/**
 * TblBrhCashInfHisId generated by hbm2java
 */
public class TblBrhCashInfHisId implements java.io.Serializable {

	private String brhId;
	private String rateId;
	private Double seqId;

	public TblBrhCashInfHisId() {
	}

	public TblBrhCashInfHisId(String brhId, String rateId, Double seqId) {
		this.brhId = brhId;
		this.rateId = rateId;
		this.seqId = seqId;
	}

	public String getBrhId() {
		return this.brhId;
	}

	public void setBrhId(String brhId) {
		this.brhId = brhId;
	}

	public String getRateId() {
		return this.rateId;
	}

	public void setRateId(String rateId) {
		this.rateId = rateId;
	}

	public Double getSeqId() {
		return this.seqId;
	}

	public void setSeqId(Double seqId) {
		this.seqId = seqId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblBrhCashInfHisId))
			return false;
		TblBrhCashInfHisId castOther = (TblBrhCashInfHisId) other;

		return ((this.getBrhId() == castOther.getBrhId()) || (this.getBrhId() != null
				&& castOther.getBrhId() != null && this.getBrhId().equals(
				castOther.getBrhId())))
				&& ((this.getRateId() == castOther.getRateId()) || (this
						.getRateId() != null && castOther.getRateId() != null && this
						.getRateId().equals(castOther.getRateId())))
				&& ((this.getSeqId() == castOther.getSeqId()) || (this
						.getSeqId() != null && castOther.getSeqId() != null && this
						.getSeqId().equals(castOther.getSeqId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getBrhId() == null ? 0 : this.getBrhId().hashCode());
		result = 37 * result
				+ (getRateId() == null ? 0 : this.getRateId().hashCode());
		result = 37 * result
				+ (getSeqId() == null ? 0 : this.getSeqId().hashCode());
		return result;
	}

}
