package com.allinfinance.po.base;
// Generated 2016-4-19 15:41:48 by Hibernate Tools 3.4.0.CR1

/**
 * TblBrhCashInfHis generated by hbm2java
 */
public class TblBrhCashInfHis implements java.io.Serializable {

	private TblBrhCashInfHisId id;
	private String name;
	private String type;
	private Double rate;
	private String crtTime;
	private String crtOpr;
	private String uptTime;
	private String uptOpr;

	public TblBrhCashInfHis() {
	}

	public TblBrhCashInfHis(TblBrhCashInfHisId id) {
		this.id = id;
	}

	public TblBrhCashInfHis(TblBrhCashInfHisId id, String name, String type,
			Double rate, String crtTime, String crtOpr, String uptTime,
			String uptOpr) {
		this.id = id;
		this.name = name;
		this.type = type;
		this.rate = rate;
		this.crtTime = crtTime;
		this.crtOpr = crtOpr;
		this.uptTime = uptTime;
		this.uptOpr = uptOpr;
	}

	public TblBrhCashInfHisId getId() {
		return this.id;
	}

	public void setId(TblBrhCashInfHisId id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Double getRate() {
		return this.rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	public String getCrtTime() {
		return this.crtTime;
	}

	public void setCrtTime(String crtTime) {
		this.crtTime = crtTime;
	}

	public String getCrtOpr() {
		return this.crtOpr;
	}

	public void setCrtOpr(String crtOpr) {
		this.crtOpr = crtOpr;
	}

	public String getUptTime() {
		return this.uptTime;
	}

	public void setUptTime(String uptTime) {
		this.uptTime = uptTime;
	}

	public String getUptOpr() {
		return this.uptOpr;
	}

	public void setUptOpr(String uptOpr) {
		this.uptOpr = uptOpr;
	}

}
